/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FADHLUR_03282024;

/**
 *
 * @author ACER
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBinggris = new javax.swing.JTextField();
        txtIlmuPenge = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 16);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(90, 20, 280, 22);

        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 70, 16);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(90, 50, 280, 22);

        jLabel3.setText("Umur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 70, 16);
        getContentPane().add(txtUmur);
        txtUmur.setBounds(90, 80, 280, 22);

        jLabel4.setText("Matematika");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 80, 16);
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(90, 110, 280, 22);

        jLabel5.setText("B. inggris");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 70, 16);

        jLabel6.setText("Ilmu Penge");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 70, 16);
        getContentPane().add(txtBinggris);
        txtBinggris.setBounds(90, 140, 280, 22);
        getContentPane().add(txtIlmuPenge);
        txtIlmuPenge.setBounds(90, 170, 280, 22);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(20, 200, 72, 23);

        jLabel7.setText("Rata - Rata");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 250, 60, 16);

        txtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilActionPerformed(evt);
            }
        });
        getContentPane().add(txtHasil);
        txtHasil.setBounds(90, 250, 280, 22);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilActionPerformed
        
        
    }//GEN-LAST:event_txtHasilActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge(Integer.parseInt(txtUmur.getText()));
        student.setmathGrade(Double.parseDouble(txtMatematika.getText()));
        student.setEnglishGrade(Double.parseDouble(txtBinggris.getText()));
        student.setScienceGrade(Double.parseDouble(txtIlmuPenge.getText()));
        txtHasil.setText(String.valueOf(student.getAverage()));
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBinggris;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtIlmuPenge;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
